// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/template.go.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorators

import (
	"context"

	"github.com/NoGambiNoBugs/gowrap-generics-examples/entity"
	"github.com/NoGambiNoBugs/gowrap-generics-examples/port"
)

// CustomerCommandTarget is an alias for port.CustomerCommand
type CustomerCommandTarget port.CustomerCommand

// CustomerCommandExample implements CustomerCommandTarget
type CustomerCommandExample struct {
	base CustomerCommandTarget
}

// Delete implements port.CustomerCommand
func (d CustomerCommandExample) Delete(ctx context.Context, input int) (output entity.Customer, err error) {
	return d.base.Delete(ctx, input)
}

// Insert implements port.CustomerCommand
func (d CustomerCommandExample) Insert(ctx context.Context, input entity.Customer) (output entity.Customer, err error) {
	return d.base.Insert(ctx, input)
}

// Update implements port.CustomerCommand
func (d CustomerCommandExample) Update(ctx context.Context, input entity.Customer) (output entity.Customer, err error) {
	return d.base.Update(ctx, input)
}

// NewCustomerCommandExample instruments an implementation of the CustomerCommandTarget
func NewCustomerCommandExample(base CustomerCommandTarget) CustomerCommandExample {
	return CustomerCommandExample{
		base: base,
	}
}
