// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/template.go.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorators

import (
	"context"

	"github.com/NoGambiNoBugs/gowrap-generics-examples/port"
)

// DeleterTarget is an alias for port.Deleter
type DeleterTarget[I, O any] port.Deleter[I, O]

// DeleterExample implements DeleterTarget
type DeleterExample[I, O any] struct {
	base DeleterTarget[I, O]
}

// Delete implements port.Deleter
func (d DeleterExample[I, O]) Delete(ctx context.Context, input I) (output O, err error) {
	return d.base.Delete(ctx, input)
}

// NewDeleterExample instruments an implementation of the DeleterTarget
func NewDeleterExample[I, O any](base DeleterTarget[I, O]) DeleterExample[I, O] {
	return DeleterExample[I, O]{
		base: base,
	}
}
