// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/template.go.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorators

import (
	"context"

	"github.com/NoGambiNoBugs/gowrap-generics-examples/port"
)

// GetterTarget is an alias for port.Getter
type GetterTarget[I, O any] port.Getter[I, O]

// GetterExample implements GetterTarget
type GetterExample[I, O any] struct {
	base GetterTarget[I, O]
}

// Get implements port.Getter
func (d GetterExample[I, O]) Get(ctx context.Context, input I) (output O, err error) {
	return d.base.Get(ctx, input)
}

// NewGetterExample instruments an implementation of the GetterTarget
func NewGetterExample[I, O any](base GetterTarget[I, O]) GetterExample[I, O] {
	return GetterExample[I, O]{
		base: base,
	}
}
