// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/template.go.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorators

import (
	"context"

	"github.com/NoGambiNoBugs/gowrap-generics-examples/port"
)

// InserterTarget is an alias for port.Inserter
type InserterTarget[I, O any] port.Inserter[I, O]

// InserterExample implements InserterTarget
type InserterExample[I, O any] struct {
	base InserterTarget[I, O]
}

// Insert implements port.Inserter
func (d InserterExample[I, O]) Insert(ctx context.Context, input I) (output O, err error) {
	return d.base.Insert(ctx, input)
}

// NewInserterExample instruments an implementation of the InserterTarget
func NewInserterExample[I, O any](base InserterTarget[I, O]) InserterExample[I, O] {
	return InserterExample[I, O]{
		base: base,
	}
}
