// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/issue_62.go.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorators

import "github.com/NoGambiNoBugs/gowrap-generics-examples/entity"

func (_d TestDecorator) MyMethod(a int, b entity.Customer) (c1 entity.Customer, err error) {
}
