// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/template.go.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorators

import (
	"context"

	"github.com/NoGambiNoBugs/gowrap-generics-examples/entity"
	"github.com/NoGambiNoBugs/gowrap-generics-examples/port"
)

// PartnerQueryTarget is an alias for port.PartnerQuery
type PartnerQueryTarget port.PartnerQuery

// PartnerQueryExample implements PartnerQueryTarget
type PartnerQueryExample struct {
	base PartnerQueryTarget
}

// Get implements port.PartnerQuery
func (d PartnerQueryExample) Get(ctx context.Context, input int) (output entity.Partner, err error) {
	return d.base.Get(ctx, input)
}

// GetByReference implements port.PartnerQuery
func (d PartnerQueryExample) GetByReference(ctx context.Context, reference string) (output entity.Partner, err error) {
	return d.base.GetByReference(ctx, reference)
}

// NewPartnerQueryExample instruments an implementation of the PartnerQueryTarget
func NewPartnerQueryExample(base PartnerQueryTarget) PartnerQueryExample {
	return PartnerQueryExample{
		base: base,
	}
}
