// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/template.go.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package decorators

import (
	"context"

	"github.com/NoGambiNoBugs/gowrap-generics-examples/entity"
	"github.com/NoGambiNoBugs/gowrap-generics-examples/port"
)

// PartnerOrderQueryTarget is an alias for port.PartnerOrderQuery
type PartnerOrderQueryTarget port.PartnerOrderQuery

// PartnerOrderQueryExample implements PartnerOrderQueryTarget
type PartnerOrderQueryExample struct {
	base PartnerOrderQueryTarget
}

// Get implements port.PartnerOrderQuery
func (d PartnerOrderQueryExample) Get(ctx context.Context, input int) (output entity.Order[entity.Partner], err error) {
	return d.base.Get(ctx, input)
}

// NewPartnerOrderQueryExample instruments an implementation of the PartnerOrderQueryTarget
func NewPartnerOrderQueryExample(base PartnerOrderQueryTarget) PartnerOrderQueryExample {
	return PartnerOrderQueryExample{
		base: base,
	}
}
